Updated default plans
sirgwain/craig-stars pull request #334
Opened 2024-08-13 18:20 UTC by Bertie690

Ported over the base battle plans from vanilla stars & improved the default production plan to only terraforming tasks if neither CA nor tri-immune (maybe a bit redundant, but it never hurts to have extra checks). 
Also renamed the default empty transport plan to "Clear All". 
Fixes issue #318

2024-08-14 01:47 UTC, sirgwain commented on cs/player.go
> +		Items: []
needs a comma

2024-08-14 01:48 UTC, sirgwain requested changes
looks good, but can you add the missing commas so it compiles?

2024-08-14 13:05 UTC, Bertie690 commented on cs/player.go
> +		Items: []
Done

2024-08-14 13:06 UTC, Bertie690 commented
Oke dokey fixed it

2024-08-14 13:39 UTC, sirgwain commented on cs/player.go
> +		Items: [],
```suggestion
		Items: []ProductionPlanItem{},
```

2024-08-14 13:48 UTC, sirgwain commented on cs/player.go
> +				AttackWho:	 BattleAttackWhoEnemiesAndNeutrals
```suggestion
				AttackWho:	 BattleAttackWhoEnemiesAndNeutrals,
```

2024-08-15 13:26 UTC, sirgwain requested changes

2024-08-15 13:26 UTC, sirgwain commented on cs/player.go
> +					Colonists: WaypointTransportTask{Action: TransportActionLoadDunnage},
Why load dunnage instead of unload all?

2024-08-15 13:45 UTC, Bertie690 commented on cs/player.go
> +					Colonists: WaypointTransportTask{Action: TransportActionLoadDunnage},
I guess I typo'd a bit...

2024-08-16 15:13 UTC, sirgwain approved these changes

2024-08-16 15:13 UTC, merged