Slot fixes
sirgwain/craig-stars pull request #429
Opened 2024-09-13 12:36 UTC by Bertie690

Very minor fixes

2024-09-13 13:55 UTC, sirgwain commented on cs/tech.go
> +	HullSlotTypeElectricalMechanical             = HullSlotTypeElectrical | HullSlotTypeMechanical
need to update the front end as well. `HullComponent.svelte` and `Tech.ts`

2024-09-17 00:31 UTC, sirgwain requested changes
There is a syntax error in shipdesign.go.  I'm not sure what you were intending with some of the changes.

2024-09-17 12:21 UTC, Bertie690 commented
oh whoops i forgot to change the title for the switch case
Mb

2024-10-08 15:58 UTC, sirgwain approved these changes

2024-10-08 15:58 UTC, merged