added cost floats to fix rounding errors again
sirgwain/craig-stars pull request #547
Opened 2024-10-22 04:38 UTC by Bertie690

Untested? Yup. 
Unnecessary? Yup. 
Worth it? Totally.

(sillies aside this introduces a new CostFloat64 struct that allows for more precise floating point calculations for previously integer-only costs. Functions will be ported over on a case-by-case basis, though it seems unlikely given that they are intended to be converted back into Costs before being passed into other major functions.)

2024-10-22 05:10 UTC, sirgwain requested changes
costFloat and its members should be unexported (lowercase). We don’t need to expose this functionality outside of the cs package. 

Also, put it in costcalculator. That’s where it’s used.

2024-10-25 01:38 UTC, Bertie690 commented
Ok i might be a tad bit obtuse... i'll need to review the code changes once I have the time. 
(Some of the test results seem cut in 2, idk why, needs testing)

2024-10-29 12:17 UTC, Bertie690 commented on cs/costcalculator.go
>  }
Need multiply by starbase cost multi methinks

2024-11-15 14:59 UTC, sirgwain approved these changes

2024-11-15 15:01 UTC, merged