Max mode Fixes + Starting starbase design func refactor
sirgwain/craig-stars pull request #586
Opened 2024-12-25 16:56 UTC by Bertie690

Fixes #580

2025-01-17 00:40 UTC, sirgwain commented on cs/universegenerator.go
> +	u := NewUniverse(ug.log, &ug.Rules); ug.Universe = &u
this should be two lines

2025-02-19 01:16 UTC, sirgwain requested changes

2025-02-19 01:16 UTC, sirgwain commented on cs/rules.go
> +	RaceLeftoverPointsPerItem                 map[SpendLeftoverPointsOn]LeftoverPointsItem `json:"raceLeftoverPointsPerItem,omitempty"`
We can change this field type. It will break loads from old games. You can rename it and it will work, but if it has the same name it has to have the same type.

2025-02-19 04:46 UTC, Bertie690 commented on cs/rules.go
> +	RaceLeftoverPointsPerItem                 map[SpendLeftoverPointsOn]LeftoverPointsItem `json:"raceLeftoverPointsPerItem,omitempty"`
Ok reverted the change.

2025-02-22 03:30 UTC, sirgwain requested changes
I tried a new test game and got a divide by zero:

```
 panic: runtime error: integer divide by zero

 -> github.com/sirgwain/craig-stars/cs.(*universeGenerator).assignRaceStartingPointBonuses
/craig-stars/cs/universegenerator.go:473
```

2025-02-22 03:31 UTC, sirgwain commented on db/upgrade.go
> +			u.initStarterDB()
we want to capture this error, we shouldn't ignore it.

2025-02-22 03:32 UTC, sirgwain commented on magefiles/launch.go
> -	mg.Deps(Generate)
we want this generate. Every time you change the server and rebuild it (with air) it should run generate.

2025-02-22 04:31 UTC, Bertie690 commented on db/upgrade.go
> +			u.initStarterDB()
To be fair, the error was quite literally being overwritten in the literal next line anyways lol.
will add it shortly in any case

2025-02-22 04:36 UTC, Bertie690 commented on magefiles/launch.go
> -	mg.Deps(Generate)
Air runs `mage build-backend` to build the binary/server, not launch it.
This is merely the command to boot air up and enable it.
Probably need to add a comment about that now don't I...

2025-02-23 16:03 UTC, sirgwain submitted a review, later dismissed

2025-02-24 14:05 UTC, sirgwain requested changes

2025-02-24 14:05 UTC, sirgwain commented on frontend/src/lib/types/Mineral.ts
> +export const AddToAll = (m: Mineral, i: number): Mineral => ({
JavaScript casing should be camelCase

2025-02-24 14:55 UTC, sirgwain submitted a review, later dismissed

2025-02-25 02:10 UTC, sirgwain approved these changes

2025-02-25 02:32 UTC, merged